// <auto-generated />
namespace IOTProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_sapxep_thongtinquanlys : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_sapxep_thongtinquanlys));
        
        string IMigrationMetadata.Id
        {
            get { return "202102030344016_add_sapxep_thongtinquanlys"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
